version: '3.8'
services:
  php:
    build:
      context: ./
      dockerfile: .docker/php/Dockerfile
    ports:
      - 9000:9000
    #volumes:
    #  - ./testapp:/var/www/test.com
    depends_on:
      mysql:
        condition: service_healthy
  
  nginx:
    image: nginx:latest
    volumes:
      - ./testapp:/var/www/test.com
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8001:80
    depends_on:
      - php
  
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 20